export const games = [
  {
    title: "Apex Legends",
    publisher: "Electronic Arts",
    date: "2018 - Present",
    services: ["Game localization"],
    platforms: ["PC", "Xbox", "Sony Play Station"],
    genre: ["Battle royale", "FPS"],
    languages: [
      "Chinese",
      "Russian",
      "Korean",
      "Spanish",
      "French",
      "Italian",
      "Swedish",
      "Catalan",
      "Japanese",
    ],
    description: "51,356 words of in-game marketing text",
    images: ["/images/games/apex.jpg", "/images/games/apex.jpg"],
  },
  {
    title: "Grime",
    publisher: "Clover Bite",
    date: "2018 - Present",
    services: ["Game localization"],
    platforms: ["PC", "Stadia"],
    genre: ["Action-adventure", "RPG"],
    languages: [
      "French",
      "Italian",
      "German",
      "Spanish",
      "Simplified Chinese",
      "Japanese",
      "Korean",
      "Brazilian Portuguese",
      "Russian",
      "Hebrew",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    images: ["/images/games/grime.jpg"],
  },
  {
    title: "Mordhau",
    publisher: "Triternion",
    date: "2018 - Present",
    services: ["Game localization"],
    platforms: ["PC"],
    genre: ["Action"],
    languages: [
      "Spanish",
      "French",
      "Italian",
      "Korean",
      "Portuguese Brazilian",
      "Russian",
      "Chinese Simplified",
      "Chinese Traditional",
      "Japanese",
      "German",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    images: ["/images/games/mordau.jpg"],
  },
  {
    title: "Murder In The Alps",
    publisher: "Nordcurrent Group",
    date: "2018 - Present",
    services: ["Game localization", "Localization testing"],
    platforms: ["PC", "Android", "IOS"],
    genre: ["Puzzle"],
    languages: [
      "German",
      "Italian",
      "Spanish",
      "Polish",
      "Portuguese (Brazilian)",
      "French",
      "Russian",
      "Japanese",
      "Korean",
      "Chinese (Simplified)",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    images: ["/images/games/murder_alps.jpg"],
  },
  {
    title: "The Crew",
    publisher: "Ubisoft",
    date: "2018 - Present",
    services: ["Game localization", "Voiceovers"],
    platforms: ["PC", "PS4", "Xbox One"],
    genre: ["Racing"],
    languages: ["Russian"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    images: ["/images/games/crew2.jpg"],
  },
  {
    title: "Dragon Storm Fantasy",
    publisher: "Goat Games",
    date: "2018 - Present",
    services: ["Game localization"],
    platforms: ["Android", "IOS"],
    genre: ["MMORPG"],
    languages: ["Russian", "German", "Turkish"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    images: ["/images/games/dragon_storm_fantasy.jpg"],
  },
  {
    title: "The Long Journey Home",
    publisher: "Daedalic Entertainment",
    date: "2018 - Present",
    services: ["Game localization", "Localization testing"],
    platforms: ["PC"],
    genre: ["Action", "Adventure"],
    languages: [
      "Russian",
      "French",
      "Korean",
      "Simplified Chinese",
      "Arabic",
      "Traditional Chinese",
      "Czech",
      "Danish",
      "Dutch",
      "Finnish",
      "Hungarian",
      "Italian",
      "Japanese",
      "Norwegian",
      "Polish",
      "Portuguese",
      "Brazilian Portuguese",
      "Spanish",
      "Swedish",
      "Thai",
      "Turkish",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    images: ["/images/games/long_journey_home.jpg"],
  },
  {
    title: "Tales of Berseria",
    publisher: "Bandai Namco",
    date: "2018 - Present",
    services: ["Game localization"],
    platforms: ["PC", "PS3", "PS4"],
    genre: ["Action", "RPG"],
    languages: [
      "Russian",
      "French",
      "Korean",
      "Simplified Chinese",
      "Arabic",
      "Traditional Chinese",
      "Czech",
      "Danish",
      "Dutch",
      "Finnish",
      "Hungarian",
      "Italian",
      "Japanese",
      "Norwegian",
      "Polish",
      "Portuguese",
      "Brazilian Portuguese",
      "Spanish",
      "Swedish",
      "Thai",
      "Turkish",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    images: ["/images/games/tales_of_berseria.jpg"],
  },
  {
    title: "The Sims 4",
    publisher: "Electronic Arts",
    date: "2018 - Present",
    services: ["Game localization"],
    platforms: ["PC", "PS4", "Xbox One"],
    genre: ["City Builder"],
    languages: ["Norwegian"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    images: ["/images/games/sims4.jpg"],
  },
  {
    title: "Turnip Boy Commits Tax Evasion",
    publisher: "Graffitti Games",
    date: "2018 - Present",
    services: ["Game localization"],
    platforms: ["PC", "Nintendo Switch"],
    genre: ["Top-down", "Action", "Adventure"],
    languages: [
      "Italian",
      "German",
      "French",
      "Simplified Chinese",
      "Spanish Latin American",
      "Russian",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    images: ["/images/games/turnip_boy.jpg"],
  },
  {
    title: "Anthem",
    publisher: "Electronic Arts",
    date: "2018 - Present",
    services: ["Game localization"],
    platforms: ["PC"],
    genre: ["MMORPG", "Adventure"],
    languages: [
      "Italian",
      "German",
      "French",
      "Simplified Chinese",
      "Spanish Latin American",
      "Russian",
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    images: ["/images/games/anthem.jpg"],
  },
  {
    title: "Crisis Action",
    publisher: "Efun",
    date: "2018 - Present",
    services: ["Game localization"],
    platforms: ["Android", "IOS"],
    genre: ["MMORPG", "Action"],
    languages: ["Russian"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    images: ["/images/games/crisis_action.jpg"],
  },
  {
    title: "Cool Game",
    publisher: "EE Games",
    date: "2018 - Present",
    services: ["Game localization"],
    platforms: ["Nintendo Switch"],
    genre: ["Match3"],
    languages: ["Russian"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    images: ["/images/games/sniper_arena.jpg"],
  },
  {
    title: "Another Cool Game",
    publisher: "EE Games",
    date: "2018 - Present",
    services: ["Game localization"],
    platforms: ["Nintendo Switch"],
    genre: ["Match3"],
    languages: ["Russian"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    images: ["/images/games/plants_vs_zombies.jpg"],
  },
  {
    title: "Classic Game",
    publisher: "EE Games",
    date: "2018 - Present",
    services: ["Game localization"],
    platforms: ["Nintendo Switch"],
    genre: ["Match3"],
    languages: ["Russian"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    images: ["/images/games/wonderful101.jpg"],
  },
];
